.TH dwarf 1 "(c) 2007-2008 Fernando Iazeolla"
.SH NAME
dwarf - a little and powerful object file manipulation tool.
.SH SYNOPSIS
.B dwarf [ options ] [ file ]
.SH DESCRIPTION
.B dwarf
is a powerful object file manipulation tools in the spirit of \fIgdb\fP. with \fIdwarf\fP you can read and edit all the file's section headers as well as the raw data. With \fIdwarf\fP you can create and customize new file's header and it can be used as a compiler back-end to create executables/object files. \fIdwarf\fP also permits to inject easily new headers and pieces of code/data into the file.
\fIdwarf\fP currently handles \fIelf\fP, \fIPE\fP (Portable executables) and \fIMach-O\fP files format. In the future new files type will be added.
.SH OPTIONS
.TP
.B -i
interactive (shell mode)
.TP
.B -c '{commands}'
command mode (executes commands)
.P
For example,
.B dwarf -c 'print 2+2;'
will output:
4
.TP
.c .B -h, --help
.c print usage info
.c .TP
.B -x < file >
loads and executes file script.
.TP
.B -t
shows the file type.
.SH SEE ALSO
readelf(1), objdump(1), ht(1), otool(1), gdb(1), elf(5)
.SH AUTHOR
.nf
Fernando Iazeolla < elboza@autistici.org > - founder & core developer.
.SH COPYRIGHT
.nf
Copyright (C) 2007-2008 Fernando Iazeolla < elboza@autistici.org >
.P
This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
.P
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
.P
You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.